name: Javascript Lint

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    javascript_lint:
        name: Javascript Linting
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 18.*
              uses: actions/setup-node@v3
              with:
                  node-version: 18.*
                  cache: 'npm'
            - run: npm ci
            - run: npm run lint:js
